import { readFile, writeFile } from "node:fs/promises";
import os from "node:os";

import type {
  BackupOverview,
  RsyncJob,
  RsyncModule,
  RsyncServer,
  SyncSchedule,
} from "@/lib/types";
import { hasCommand, runArgs, USE_MOCK } from "./exec";
import { emitEvent } from "./notify";

function notifyJob(job: RsyncJob) {
  if (job.lastStatus === "failed") {
    void emitEvent("backup.failed", "critical", `백업 실패: ${job.name}`, job.lastError ?? "rsync 작업이 실패했습니다.");
  } else if (job.lastStatus === "success") {
    void emitEvent("backup.success", "info", `백업 완료: ${job.name}`, `${formatBytesShort(job.lastBytes)} · ${job.lastFiles}개 파일 전송`);
  }
}

function formatBytesShort(b: number): string {
  if (b > 1024 ** 3) return (b / 1024 ** 3).toFixed(1) + " GB";
  if (b > 1024 ** 2) return (b / 1024 ** 2).toFixed(0) + " MB";
  return (b / 1024).toFixed(0) + " KB";
}

const GiB = 1024 ** 3;
const RSYNC_CONF = process.env.RSYNC_CONF ?? "/etc/rsyncd.conf";

const SCHED_MS: Record<Exclude<SyncSchedule, "manual">, number> = {
  hourly: 3600_000,
  daily: 86_400_000,
  weekly: 604_800_000,
};

// Safe-ish charset for rsync remote/local endpoints (no shell metacharacters).
const ENDPOINT_RE = /^[A-Za-z0-9@._:\-/~]+$/;
const NAME_RE = /^[A-Za-z0-9][A-Za-z0-9_\- ]*$/;

interface State {
  jobs: RsyncJob[];
  enabled: boolean;
  port: number;
  modules: RsyncModule[];
}

// Demo seed data — used ONLY in mock/dev mode (USE_MOCK). In real mode these
// app-managed lists start EMPTY and modules are parsed from the live system.
const DEMO_JOBS: RsyncJob[] = [
  {
    id: "job-1",
    name: "사진 원격 백업",
    direction: "push",
    remote: "backup@nas2.local:/volume1/photos",
    localPath: "/volume1/Photos",
    archive: true,
    compress: true,
    deleteExtra: false,
    schedule: "daily",
    lastRun: Date.now() - 11 * 3600_000,
    lastStatus: "success",
    lastBytes: 4.2 * GiB,
    lastFiles: 1284,
    nextRun: Date.now() + 13 * 3600_000,
  },
  {
    id: "job-2",
    name: "오프사이트에서 문서 가져오기",
    direction: "pull",
    remote: "rsync://offsite.example.com/documents",
    localPath: "/volume1/Documents",
    archive: true,
    compress: true,
    deleteExtra: true,
    schedule: "hourly",
    lastRun: Date.now() - 26 * 60_000,
    lastStatus: "success",
    lastBytes: 88 * 1024 * 1024,
    lastFiles: 42,
    nextRun: Date.now() + 34 * 60_000,
  },
  {
    id: "job-3",
    name: "미디어 → 콜드 스토리지",
    direction: "push",
    remote: "cold@10.0.0.9:/mnt/cold/media",
    localPath: "/volume1/Movies",
    archive: true,
    compress: false,
    deleteExtra: false,
    schedule: "weekly",
    lastRun: Date.now() - 3 * 86_400_000,
    lastStatus: "failed",
    lastBytes: 0,
    lastFiles: 0,
    lastError: "ssh: connect to host 10.0.0.9 port 22: Connection timed out",
    nextRun: Date.now() + 4 * 86_400_000,
  },
];

const DEMO_MODULES: RsyncModule[] = [
  { name: "media", path: "/volume1/Movies", readOnly: true, comment: "Read-only media library", hostsAllow: "192.168.1.0/24" },
  { name: "backup", path: "/volume1/Backups", readOnly: false, comment: "Backup target", hostsAllow: "192.168.1.0/24 10.0.0.0/8" },
  { name: "public", path: "/volume2/Media", readOnly: false, comment: "Public drop", hostsAllow: "*" },
];

const state: State = {
  jobs: USE_MOCK ? DEMO_JOBS : [],
  enabled: true,
  port: 873,
  modules: USE_MOCK ? DEMO_MODULES : [],
};

function generateConf(): string {
  const lines = [
    "# Generated by Nimbo",
    "uid = nobody",
    "gid = nogroup",
    "use chroot = yes",
    "max connections = 10",
    `port = ${state.port}`,
    "",
  ];
  for (const m of state.modules) {
    lines.push(`[${m.name}]`);
    lines.push(`    path = ${m.path}`);
    if (m.comment) lines.push(`    comment = ${m.comment}`);
    lines.push(`    read only = ${m.readOnly ? "yes" : "no"}`);
    lines.push(`    hosts allow = ${m.hostsAllow || "*"}`);
    lines.push("");
  }
  return lines.join("\n");
}

/**
 * Best-effort parse of a real rsyncd.conf into modules. Unknown/global keys are
 * ignored; only `[module]` sections with a `path` become modules. Returns [] on
 * any read/parse failure so real mode never invents modules.
 */
async function parseRealModules(): Promise<RsyncModule[]> {
  let text: string;
  try {
    text = await readFile(RSYNC_CONF, "utf8");
  } catch {
    return [];
  }
  const modules: RsyncModule[] = [];
  let current: RsyncModule | null = null;
  for (const rawLine of text.split("\n")) {
    const line = rawLine.replace(/[#;].*$/, "").trim();
    if (!line) continue;
    const section = line.match(/^\[(.+)\]$/);
    if (section) {
      if (current && current.path) modules.push(current);
      current = { name: section[1].trim(), path: "", readOnly: true, comment: "", hostsAllow: "*" };
      continue;
    }
    if (!current) continue;
    const kv = line.match(/^([^=]+?)\s*=\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1].trim().toLowerCase();
    const value = kv[2].trim();
    if (key === "path") current.path = value;
    else if (key === "comment") current.comment = value;
    else if (key === "read only") current.readOnly = /^(yes|true|1)$/i.test(value);
    else if (key === "hosts allow") current.hostsAllow = value;
  }
  if (current && current.path) modules.push(current);
  return modules;
}

function buildServer(): RsyncServer {
  return { enabled: state.enabled, port: state.port, modules: state.modules, generatedConf: generateConf() };
}

export async function getBackupOverview(): Promise<BackupOverview> {
  startScheduler();
  let rsyncAvailable = true;
  let enabled = state.enabled;
  if (!USE_MOCK) {
    rsyncAvailable = await hasCommand("rsync");
    // Reflect the real daemon status when possible.
    const { code } = await runArgs("systemctl", ["is-active", "--quiet", "rsync"]);
    enabled = code === 0;
    state.enabled = enabled;
    // Reflect the real server config: modules come from /etc/rsyncd.conf only.
    state.modules = await parseRealModules();
  }
  return {
    jobs: state.jobs,
    server: buildServer(),
    rsyncAvailable,
    hostname: USE_MOCK ? "nas-server" : os.hostname(),
    isMock: USE_MOCK,
  };
}

// --------------------------------------------------------------------------
// Actions
// --------------------------------------------------------------------------
export interface BackupAction {
  kind: string;
  id?: string;
  job?: Partial<RsyncJob>;
  module?: RsyncModule;
  name?: string;
  enabled?: boolean;
}

function ok() {
  return { ok: true as const };
}
function fail(error: string) {
  return { ok: false as const, error };
}

export async function runBackupAction(a: BackupAction): Promise<{ ok: boolean; error?: string }> {
  switch (a.kind) {
    case "job.create": {
      const j = a.job ?? {};
      if (!j.name || !NAME_RE.test(j.name)) return fail("invalid name");
      if (!j.remote || !ENDPOINT_RE.test(j.remote)) return fail("invalid remote");
      if (!j.localPath || !ENDPOINT_RE.test(j.localPath)) return fail("invalid local path");
      const id = `job-${Date.now()}`;
      const schedule = (j.schedule ?? "manual") as SyncSchedule;
      state.jobs.push({
        id,
        name: j.name,
        direction: j.direction === "pull" ? "pull" : "push",
        remote: j.remote,
        localPath: j.localPath,
        archive: j.archive ?? true,
        compress: j.compress ?? true,
        deleteExtra: j.deleteExtra ?? false,
        schedule,
        lastRun: null,
        lastStatus: "idle",
        lastBytes: 0,
        lastFiles: 0,
        nextRun: schedule === "manual" ? null : Date.now() + SCHED_MS[schedule],
      });
      return ok();
    }
    case "job.update": {
      const job = state.jobs.find((x) => x.id === a.id);
      if (!job || !a.job) return fail("not found");
      const j = a.job;
      if (j.remote && !ENDPOINT_RE.test(j.remote)) return fail("invalid remote");
      if (j.localPath && !ENDPOINT_RE.test(j.localPath)) return fail("invalid local path");
      Object.assign(job, {
        name: j.name ?? job.name,
        direction: j.direction ?? job.direction,
        remote: j.remote ?? job.remote,
        localPath: j.localPath ?? job.localPath,
        archive: j.archive ?? job.archive,
        compress: j.compress ?? job.compress,
        deleteExtra: j.deleteExtra ?? job.deleteExtra,
        schedule: j.schedule ?? job.schedule,
      });
      job.nextRun = job.schedule === "manual" ? null : Date.now() + SCHED_MS[job.schedule];
      return ok();
    }
    case "job.delete":
      state.jobs = state.jobs.filter((x) => x.id !== a.id);
      return ok();
    case "job.run": {
      const job = state.jobs.find((x) => x.id === a.id);
      if (!job) return fail("not found");
      return runJob(job);
    }
    case "server.toggle": {
      state.enabled = a.enabled ?? !state.enabled;
      if (!USE_MOCK) {
        const args = state.enabled ? ["enable", "--now", "rsync"] : ["disable", "--now", "rsync"];
        const { code, stderr } = await runArgs("systemctl", args, { timeoutMs: 15000 });
        if (code !== 0) return fail(stderr.trim() || "needs root/sudoers");
      }
      return ok();
    }
    case "module.create": {
      const m = a.module;
      if (!m || !NAME_RE.test(m.name) || !ENDPOINT_RE.test(m.path)) return fail("invalid module");
      if (state.modules.some((x) => x.name === m.name)) return fail("module exists");
      state.modules.push(m);
      return persistConf();
    }
    case "module.delete":
      state.modules = state.modules.filter((m) => m.name !== a.name);
      return persistConf();
    default:
      return fail("unknown action");
  }
}

async function persistConf(): Promise<{ ok: boolean; error?: string }> {
  if (USE_MOCK) return ok();
  try {
    await writeFile(RSYNC_CONF, generateConf(), "utf8");
    await runArgs("systemctl", ["reload-or-restart", "rsync"]);
    return ok();
  } catch (err) {
    return fail((err as Error).message + " — needs root to write " + RSYNC_CONF);
  }
}

function parseStats(output: string): { bytes: number; files: number } {
  const filesM = output.match(/Number of regular files transferred:\s*([\d,]+)/) ||
    output.match(/Number of files transferred:\s*([\d,]+)/);
  const bytesM = output.match(/Total transferred file size:\s*([\d,]+)/);
  return {
    files: filesM ? Number(filesM[1].replace(/,/g, "")) : 0,
    bytes: bytesM ? Number(bytesM[1].replace(/,/g, "")) : 0,
  };
}

function pushHistory(job: RsyncJob, durationMs: number) {
  const rec = { ts: job.lastRun ?? Date.now(), status: job.lastStatus, bytes: job.lastBytes, files: job.lastFiles, durationMs };
  job.history = [rec, ...(job.history ?? [])].slice(0, 20);
}

async function runJob(job: RsyncJob): Promise<{ ok: boolean; error?: string }> {
  job.lastStatus = "running";
  const started = Date.now();
  if (USE_MOCK) {
    // Simulate a successful transfer with plausible stats.
    const failHost = /timed out|10\.0\.0\.9/.test(job.remote);
    job.lastRun = Date.now();
    const src = job.direction === "pull" ? job.remote : job.localPath;
    const dst = job.direction === "pull" ? job.localPath : job.remote;
    if (failHost && job.id === "job-3") {
      job.lastStatus = "failed";
      job.lastError = "ssh: connect to host: Connection timed out";
      job.lastLog = `sending incremental file list\nrsync: connection unexpectedly closed\nrsync error: unexplained error (code 255) at io.c(235)\n${job.lastError}`;
    } else {
      job.lastStatus = "success";
      job.lastError = undefined;
      job.lastFiles = 20 + Math.floor((job.localPath.length * 37) % 400);
      job.lastBytes = (0.2 + ((job.name.length * 13) % 50) / 10) * GiB;
      job.lastLog = [
        `rsync ${job.archive ? "-a" : "-r"}${job.compress ? "z" : ""}${job.deleteExtra ? " --delete" : ""} --stats ${src} ${dst}`,
        "sending incremental file list",
        "./",
        "IMG_4821.heic", "IMG_4822.heic", "report-2026-Q2.pdf", "...",
        "",
        `Number of files transferred: ${job.lastFiles}`,
        `Total transferred file size: ${job.lastBytes} bytes`,
        `sent ${Math.round(job.lastBytes * 1.01)} bytes  received 4,210 bytes  ${(job.lastBytes / 1e6 * 2).toFixed(0)} bytes/sec`,
        "total size is " + Math.round(job.lastBytes * 3) + "  speedup is 2.97",
      ].join("\n");
    }
    pushHistory(job, Date.now() - started + 1200);
    notifyJob(job);
    if (job.schedule !== "manual") job.nextRun = Date.now() + SCHED_MS[job.schedule];
    return job.lastStatus === "success" ? ok() : fail(job.lastError ?? "failed");
  }

  const src = job.direction === "pull" ? job.remote : job.localPath;
  const dst = job.direction === "pull" ? job.localPath : job.remote;
  if (!ENDPOINT_RE.test(src) || !ENDPOINT_RE.test(dst)) {
    job.lastStatus = "failed";
    return fail("invalid endpoint");
  }
  const flagArgs = [job.archive ? "-a" : "-r", job.compress ? "-z" : "", job.deleteExtra ? "--delete" : "", "--stats"].filter(Boolean);
  const flags = flagArgs.join(" ");
  const { stdout, code, stderr } = await runArgs("rsync", [...flagArgs, src, dst], { timeoutMs: 10 * 60_000 });
  job.lastRun = Date.now();
  job.lastLog = (`$ rsync ${flags} ${src} ${dst}\n\n` + stdout + (stderr ? "\n" + stderr : "")).slice(-8000);
  if (code === 0) {
    const { bytes, files } = parseStats(stdout);
    job.lastStatus = "success";
    job.lastBytes = bytes;
    job.lastFiles = files;
    job.lastError = undefined;
  } else {
    job.lastStatus = "failed";
    job.lastError = stderr.trim().split("\n").slice(-1)[0] || "rsync failed";
  }
  pushHistory(job, Date.now() - started + 1);
  notifyJob(job);
  if (job.schedule !== "manual") job.nextRun = Date.now() + SCHED_MS[job.schedule];
  return code === 0 ? ok() : fail(job.lastError ?? "failed");
}

// --------------------------------------------------------------------------
// Scheduler
// --------------------------------------------------------------------------
let tickerStarted = false;
function startScheduler() {
  if (tickerStarted) return;
  tickerStarted = true;
  setInterval(() => {
    const now = Date.now();
    for (const job of state.jobs) {
      if (job.schedule === "manual" || job.nextRun == null || job.nextRun > now) continue;
      if (job.lastStatus === "running") continue;
      runJob(job).catch(() => {});
    }
  }, 60_000);
}
