import { readFile, writeFile } from "node:fs/promises";

import type { FileServices, SharedFolder, SharesAdminOverview } from "@/lib/types";
import { run, USE_MOCK } from "./exec";

const GiB = 1024 ** 3;

const SMB_CONF = process.env.SMB_CONF ?? "/etc/samba/smb.conf.d/shares.conf";
const NFS_EXPORTS = process.env.NFS_EXPORTS ?? "/etc/exports.d/nas.exports";

// Validation charsets (no shell metacharacters).
const NAME_RE = /^[A-Za-z0-9][A-Za-z0-9_\- ]*$/;
const PATH_RE = /^[A-Za-z0-9._\-/]+$/;

interface State {
  folders: SharedFolder[];
  services: FileServices;
}

// Seeded demo shares — used ONLY in mock/dev mode. On a real host shares are
// parsed from /etc/samba + /etc/exports and services from systemctl; we never
// invent demo folders.
function seedFolders(): SharedFolder[] {
  return [
    {
      name: "Movies",
      path: "/volume1/Movies",
      description: "영화 라이브러리",
      smbEnabled: true,
      nfsEnabled: false,
      readOnly: true,
      guestOk: false,
      validUsers: "",
      usedBytes: 842 * GiB,
    },
    {
      name: "Photos",
      path: "/volume1/Photos",
      description: "가족 사진 보관함",
      smbEnabled: true,
      nfsEnabled: true,
      readOnly: false,
      guestOk: false,
      validUsers: "",
      usedBytes: 318 * GiB,
    },
    {
      name: "Backups",
      path: "/volume1/Backups",
      description: "클라이언트 백업 대상",
      smbEnabled: true,
      nfsEnabled: false,
      readOnly: true,
      guestOk: false,
      validUsers: "@backup",
      usedBytes: 1204 * GiB,
    },
    {
      name: "Public",
      path: "/volume1/Public",
      description: "게스트 공용 공유",
      smbEnabled: true,
      nfsEnabled: false,
      readOnly: false,
      guestOk: true,
      validUsers: "",
      usedBytes: 47 * GiB,
    },
    {
      name: "Media",
      path: "/volume2/Media",
      description: "NFS 미디어 스트리밍",
      smbEnabled: false,
      nfsEnabled: true,
      readOnly: false,
      guestOk: false,
      validUsers: "",
      usedBytes: 1536 * GiB,
    },
  ];
}

const state: State = {
  folders: USE_MOCK ? seedFolders() : [],
  services: USE_MOCK ? { smb: true, nfs: true, afp: false } : { smb: false, nfs: false, afp: false },
};

// --------------------------------------------------------------------------
// Config generation
// --------------------------------------------------------------------------
function generateSmbConf(): string {
  const lines = ["# Generated by Nimbo", ""];
  for (const f of state.folders) {
    if (!f.smbEnabled) continue;
    lines.push(`[${f.name}]`);
    if (f.description) lines.push(`    comment = ${f.description}`);
    lines.push(`    path = ${f.path}`);
    lines.push(`    read only = ${f.readOnly ? "yes" : "no"}`);
    lines.push(`    guest ok = ${f.guestOk ? "yes" : "no"}`);
    if (f.validUsers.trim()) lines.push(`    valid users = ${f.validUsers.trim()}`);
    lines.push("");
  }
  return lines.join("\n");
}

function generateExportsConf(): string {
  const lines = ["# Generated by Nimbo"];
  for (const f of state.folders) {
    if (!f.nfsEnabled) continue;
    const mode = f.readOnly ? "ro" : "rw";
    lines.push(`${f.path} *(${mode},sync,no_subtree_check)`);
  }
  return lines.join("\n") + "\n";
}

// --------------------------------------------------------------------------
// Real-system parsing (best-effort)
// --------------------------------------------------------------------------
function parseSmbFolders(text: string): Map<string, SharedFolder> {
  const map = new Map<string, SharedFolder>();
  let current: SharedFolder | null = null;
  const flush = () => {
    if (current && current.path) map.set(current.name, current);
  };
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#") || line.startsWith(";")) continue;
    const section = line.match(/^\[(.+)\]$/);
    if (section) {
      flush();
      const name = section[1];
      if (name.toLowerCase() === "global") {
        current = null;
        continue;
      }
      current = {
        name,
        path: "",
        description: "",
        smbEnabled: true,
        nfsEnabled: false,
        readOnly: false,
        guestOk: false,
        validUsers: "",
        usedBytes: 0,
      };
      continue;
    }
    if (!current) continue;
    const kv = line.match(/^([\w ]+)=(.*)$/);
    if (!kv) continue;
    const key = kv[1].trim().toLowerCase();
    const value = kv[2].trim();
    if (key === "path") current.path = value;
    if (key === "comment") current.description = value;
    if (key === "read only") current.readOnly = /yes|true/i.test(value);
    if (key === "writable" || key === "writeable") current.readOnly = !/yes|true/i.test(value);
    if (key === "guest ok" || key === "public") current.guestOk = /yes|true/i.test(value);
    if (key === "valid users") current.validUsers = value;
  }
  flush();
  return map;
}

function parseExportPaths(text: string): { path: string; readOnly: boolean }[] {
  const out: { path: string; readOnly: boolean }[] = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const m = line.match(/^(\S+)\s+(.*)$/);
    if (!m) continue;
    out.push({ path: m[1], readOnly: /\bro\b/.test(m[2]) });
  }
  return out;
}

async function loadRealFolders(): Promise<SharedFolder[]> {
  const byName = new Map<string, SharedFolder>();
  try {
    const smb = await readFile(SMB_CONF, "utf8");
    for (const [name, folder] of parseSmbFolders(smb)) byName.set(name, folder);
  } catch {
    // samba shares not configured
  }
  try {
    const exp = await readFile(NFS_EXPORTS, "utf8");
    for (const e of parseExportPaths(exp)) {
      const name = e.path.split("/").filter(Boolean).pop() || e.path;
      const existing = [...byName.values()].find((f) => f.path === e.path);
      if (existing) {
        existing.nfsEnabled = true;
      } else {
        byName.set(name, {
          name,
          path: e.path,
          description: "",
          smbEnabled: false,
          nfsEnabled: true,
          readOnly: e.readOnly,
          guestOk: false,
          validUsers: "",
          usedBytes: 0,
        });
      }
    }
  } catch {
    // nfs exports not configured
  }
  return [...byName.values()];
}

async function isActive(unit: string): Promise<boolean> {
  const { code } = await run(`systemctl is-active --quiet ${unit}`);
  return code === 0;
}

// --------------------------------------------------------------------------
// Overview
// --------------------------------------------------------------------------
export async function getSharesAdminOverview(): Promise<SharesAdminOverview> {
  if (USE_MOCK) {
    return {
      folders: state.folders,
      services: state.services,
      smbConf: generateSmbConf(),
      exportsConf: generateExportsConf(),
      isMock: true,
    };
  }
  const real = await loadRealFolders();
  if (real.length) state.folders = real;
  state.services = {
    smb: await isActive("smbd"),
    nfs: await isActive("nfs-server"),
    afp: await isActive("netatalk"),
  };
  return {
    folders: state.folders,
    services: state.services,
    smbConf: generateSmbConf(),
    exportsConf: generateExportsConf(),
    isMock: false,
  };
}

// --------------------------------------------------------------------------
// Actions
// --------------------------------------------------------------------------
export interface SharesAction {
  kind: string;
  name?: string;
  folder?: SharedFolder;
  service?: "smb" | "nfs" | "afp";
  enabled?: boolean;
}

function ok() {
  return { ok: true as const };
}
function fail(error: string) {
  return { ok: false as const, error };
}

const SERVICE_UNIT: Record<"smb" | "nfs" | "afp", string> = {
  smb: "smbd",
  nfs: "nfs-server",
  afp: "netatalk",
};

function validateFolder(f: SharedFolder | undefined): string | null {
  if (!f) return "folder required";
  if (!f.name || !NAME_RE.test(f.name)) return "invalid name";
  if (!f.path || !PATH_RE.test(f.path)) return "invalid path";
  return null;
}

function normalizeFolder(f: SharedFolder): SharedFolder {
  return {
    name: f.name.trim(),
    path: f.path.trim(),
    description: (f.description ?? "").trim(),
    smbEnabled: !!f.smbEnabled,
    nfsEnabled: !!f.nfsEnabled,
    readOnly: !!f.readOnly,
    guestOk: !!f.guestOk,
    validUsers: (f.validUsers ?? "").trim(),
    usedBytes: typeof f.usedBytes === "number" ? f.usedBytes : 0,
  };
}

export async function runSharesAction(a: SharesAction): Promise<{ ok: boolean; error?: string }> {
  switch (a.kind) {
    case "folder.create": {
      const err = validateFolder(a.folder);
      if (err) return fail(err);
      const folder = normalizeFolder(a.folder!);
      if (state.folders.some((f) => f.name === folder.name)) return fail("이미 존재하는 공유 폴더입니다.");
      state.folders = [...state.folders, folder];
      return persistConf();
    }
    case "folder.update": {
      if (!a.name) return fail("name required");
      const err = validateFolder(a.folder);
      if (err) return fail(err);
      const idx = state.folders.findIndex((f) => f.name === a.name);
      if (idx === -1) return fail("not found");
      const merged = normalizeFolder({ ...state.folders[idx], ...a.folder! });
      state.folders = state.folders.map((f, i) => (i === idx ? merged : f));
      return persistConf();
    }
    case "folder.delete": {
      if (!a.name) return fail("name required");
      state.folders = state.folders.filter((f) => f.name !== a.name);
      return persistConf();
    }
    case "service.toggle": {
      const svc = a.service;
      if (!svc || !(svc in SERVICE_UNIT)) return fail("invalid service");
      const enabled = a.enabled ?? !state.services[svc];
      if (!USE_MOCK) {
        const unit = SERVICE_UNIT[svc];
        const cmd = enabled ? `systemctl enable --now ${unit}` : `systemctl disable --now ${unit}`;
        const { code, stderr } = await run(cmd, { timeoutMs: 15000 });
        if (code !== 0) return fail(stderr.trim() || "권한 필요");
      }
      state.services = { ...state.services, [svc]: enabled };
      return ok();
    }
    default:
      return fail("unknown action");
  }
}

async function persistConf(): Promise<{ ok: boolean; error?: string }> {
  if (USE_MOCK) return ok();
  try {
    await writeFile(SMB_CONF, generateSmbConf(), "utf8");
    await writeFile(NFS_EXPORTS, generateExportsConf(), "utf8");
    await run("systemctl reload-or-restart smbd");
    await run("exportfs -ra");
    return ok();
  } catch (err) {
    return fail((err as Error).message + " — needs root to write shares config");
  }
}
