import { writeFile } from "node:fs/promises";
import os from "node:os";

import type { TimeMachineOverview, TimeMachineTarget } from "@/lib/types";
import { run, USE_MOCK } from "./exec";

const TiB = 1024 ** 4;
const SMB_TM_CONF = process.env.SMB_TM_CONF ?? "/etc/samba/smb.conf.d/timemachine.conf";

// Validation charsets (no shell metacharacters; spaces allowed in names).
const NAME_RE = /^[A-Za-z0-9][A-Za-z0-9_\- ]*$/;
const PATH_RE = /^[A-Za-z0-9._\-/]+$/;

interface State {
  enabled: boolean;
  targets: TimeMachineTarget[];
}

// Demo seed data — used ONLY in mock/dev mode (USE_MOCK). In real mode targets
// start EMPTY and are managed by the app / reflected from the live config.
const DEMO_TARGETS: TimeMachineTarget[] = [
  {
    id: "tm-1",
    name: "맥북프로 백업",
    path: "/volume1/TimeMachine",
    quotaBytes: 2 * TiB,
    usedBytes: 0.8 * TiB,
    enabled: true,
  },
  {
    id: "tm-2",
    name: "아이맥 백업",
    path: "/volume1/TimeMachine-iMac",
    quotaBytes: null,
    usedBytes: 1.2 * TiB,
    enabled: true,
  },
];

const state: State = {
  enabled: true,
  targets: USE_MOCK ? DEMO_TARGETS : [],
};

/**
 * Build a Samba smb.conf snippet that exposes the enabled Time Machine targets
 * over SMB using the Apple `fruit` + `streams_xattr` VFS objects.
 */
function generateConf(): string {
  const lines = [
    "# Generated by Nimbo — Time Machine over SMB",
    "# Add to /etc/samba/smb.conf — requires in [global]:",
    "#   vfs objects = catia fruit streams_xattr",
    "#   fruit:metadata = stream",
    "#   fruit:model = TimeCapsule6",
    "#   fruit:posix_rename = yes",
    "#   fruit:veto_appledouble = no",
    "#   fruit:nfs_aces = no",
    "#   fruit:wipe_intentionally_left_blank_rfork = yes",
    "#   fruit:delete_empty_adfiles = yes",
    "",
  ];
  for (const t of state.targets) {
    if (!t.enabled) continue;
    lines.push(`[${t.name}]`);
    lines.push(`   path = ${t.path}`);
    lines.push("   valid users = @backup");
    lines.push("   read only = no");
    lines.push("   vfs objects = catia fruit streams_xattr");
    lines.push("   fruit:time machine = yes");
    if (t.quotaBytes != null) {
      const sizeT = Math.round(t.quotaBytes / TiB);
      lines.push(`   fruit:time machine max size = ${sizeT}T`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** Best-effort disk usage of a path via `du -sb`. Falls back to 0. */
async function diskUsage(path: string): Promise<number> {
  if (!PATH_RE.test(path)) return 0;
  const { stdout, code } = await run(`du -sb ${path}`);
  if (code !== 0) return 0;
  const m = stdout.match(/^(\d+)/);
  return m ? Number(m[1]) : 0;
}

export async function getTimeMachineOverview(): Promise<TimeMachineOverview> {
  let enabled = state.enabled;
  if (!USE_MOCK) {
    // Reflect the real smbd status when possible.
    const { code } = await run("systemctl is-active --quiet smbd");
    enabled = code === 0;
    state.enabled = enabled;
    // Best-effort refresh of used bytes per target.
    for (const t of state.targets) {
      t.usedBytes = await diskUsage(t.path);
    }
  }
  return {
    enabled: state.enabled,
    targets: state.targets,
    generatedConf: generateConf(),
    hostname: USE_MOCK ? "nas-server" : os.hostname(),
    isMock: USE_MOCK,
  };
}

// --------------------------------------------------------------------------
// Actions
// --------------------------------------------------------------------------
export interface TmAction {
  kind: string;
  id?: string;
  enabled?: boolean;
  target?: { name?: string; path?: string; quotaBytes?: number | null };
}

function ok() {
  return { ok: true as const };
}
function fail(error: string) {
  return { ok: false as const, error };
}

export async function runTimeMachineAction(a: TmAction): Promise<{ ok: boolean; error?: string }> {
  switch (a.kind) {
    case "tm.toggle": {
      state.enabled = a.enabled ?? !state.enabled;
      if (!USE_MOCK) {
        const result = await persistConf();
        if (!result.ok) return result;
      }
      return ok();
    }
    case "target.create": {
      const t = a.target;
      if (!t || !t.name || !NAME_RE.test(t.name)) return fail("invalid name");
      if (!t.path || !PATH_RE.test(t.path)) return fail("invalid path");
      state.targets.push({
        id: `tm-${Date.now()}`,
        name: t.name,
        path: t.path,
        quotaBytes: t.quotaBytes ?? null,
        usedBytes: 0,
        enabled: true,
      });
      return persistConf();
    }
    case "target.delete": {
      state.targets = state.targets.filter((x) => x.id !== a.id);
      return persistConf();
    }
    case "target.toggle": {
      const target = state.targets.find((x) => x.id === a.id);
      if (!target) return fail("not found");
      target.enabled = a.enabled ?? !target.enabled;
      return persistConf();
    }
    default:
      return fail("unknown action");
  }
}

async function persistConf(): Promise<{ ok: boolean; error?: string }> {
  if (USE_MOCK) return ok();
  try {
    await writeFile(SMB_TM_CONF, generateConf(), "utf8");
    await run("systemctl reload-or-restart smbd");
    return ok();
  } catch (err) {
    return fail((err as Error).message + " — needs root to write " + SMB_TM_CONF);
  }
}
